language: csharp
mono: none
dotnet: 2.1.100
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2
    - dotnet-sdk-2.1
  #sonarcloud:
    #organisation: "andersen27"
    
install:
  - export COVERALLSNET_EXEPATH=/home/travis/build/csMACnz/coveralls.net/Package/Archive/linux/csmacnz.Coveralls
  - dotnet restore ./csmacnz.Coveralls.sln
  
script:
  - dotnet build ./csmacnz.Coveralls.sln -c Release
  - dotnet test ./src/csmacnz.Coveralls.Tests/csmacnz.Coveralls.Tests.csproj -c Release
 #- sonar-scanner