language: csharp
mono: none
dotnet: 2.1.200
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2
    - dotnet-sdk-2.1
  
script:
  #- dotnet build ./TextCensoring.sln -c Release
  #- dotnet test ./UnitTest/UnitTest.csproj -c Release
  "sbt clean coverage test"

after_success: "sbt coveralls"